---
- hosts: all
  roles:

  # fonts
#  - role: cask_package
#    tap: caskroom/fonts
#    package_name: font-source-code-pro
#  - role: cask_package
#    tap: caskroom/fonts
#    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
#  - role: git
#    git_user_name: Bob Bob
#    git_user_email: bob.bob@example.com
#  - role: legit
#  - role: hub
  - role: brew_package
    package_name: vim
  ## languages
#  - role: brew_package
#    package_name: node
#  - role: rbenv
#  - role: npm_package
#    package_name: grunt
#  - role: npm_package
#    package_name: bower
  - role: cask_package
    package_name: java
#  - role: brew_package
#    package_name: android-sdk
  ## databases
#  - role: brew_package
#    package_name: postgres
#  - role: brew_package
#    package_name: mongodb
  ## deployment
#  - role: brew_package
#    package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
#  - role: cask_package
#    package_name: atom
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: iterm2
  - role: cask_package
    package_name: github
  - role: cask_package
    package_name: skype
  - role: cask_package
    package_name: slack
  - role: cask_package
    package_name: textwrangler
  - role: cask_package
    package_name: gimp
  - role: cask_package
    package_name: spotify
  - role: cask_package
    package_name: keepassx
  - role: cask_package
    package_name: adium
  - role: cask_package
    package_name: vlc
  - role: cask_package
    package_name: seafile-client

  # osx config
  - role: dock
    apps:
    - /Applications/Mail.app
    - /Applications/Calendar.app
    - /Applications/Firefox.app
    - /Applications/Safari.app
    - /Applications/Adium.app
    - /Applications/Skype.app
    - /Applications/Slack.app
    - /Applications/TextWrangler.app
    - /Applications/GitHub.app
    - /Applications/iTerm.app
    - /Applications/System\ Preferences.app
    - /Applications/KeePassX.app
    - /Applications/Spotify.app
    - /Applications/VLC.app
    - /Applications/Utilities/Activity\ Monitor.app
#    - /Applications/Airmail.app
#    - /Applications/Dashlane.app
#    - /Applications/Airmail.app
#    - /Applications/Atom.app
#    - /Applications/Dash.app
    folders:
#    - path: ~/
    - path: /Applications
#    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
#  - role: cask_package
#    package_name: asepsis
  - role: dashboard
    disabled: YES

